coverage:
  status:
    patch: off
    project:
      default:
        # basic
        target: 80%
        threshold: 10%
        base: auto
        flags:
          - unit
        paths:
          - "src"
        # advanced
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
